import { supabase } from './models/supabase.js';

async function createTable() {
  const sql = `
    CREATE TABLE IF NOT EXISTS public.counseling_kakao_send_history (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      student_id BIGINT REFERENCES public.students(id) ON DELETE CASCADE,
      receiver_type TEXT NOT NULL,
      receiver_phone TEXT NOT NULL,
      send_status TEXT NOT NULL,
      error_message TEXT,
      send_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    );
  `;
  const { data, error } = await supabase.rpc('run_sql', { query: sql });
  if (error) {
    console.error('Error creating table:', error.message);
    
    // Fallback: Just try to query it again in case it exists but was not showing, though it said not found.
    // If we don't have run_sql, we need to instruct the user to run this in their Supabase dashboard.
  } else {
    console.log('Table created successfully:', data);
  }
}
createTable();
